name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Install LISP
      run: sudo apt-get install -y sbcl cl-quicklisp
    
    - name: Quicklisp dependencies
      run: make dependencies
      
    - name: Run tests
      run: make test
      
    - name: Build
      run: make build
